version: 1

environment:
  php: 7.4
  node: 16

services:
  - mysql: 10.2
  - redis:

pipeline:
  - name: Setup
    cmd: |
      cp -v .env.example .env
      composer install --no-interaction --prefer-dist --optimize-autoloader
      php artisan key:generate

  - name: Compile Dev Assets
    cmd: |
      npm ci --no-audit
      npm run dev

  - name: Test
    cmd: phpunit
